<?php
return array (
  'DB_TYPE' => 'mysql',
  'DB_HOST' => 'localhost',
  'DB_NAME' => 'sq_test',
  'DB_USER' => 'root', 
  'DB_PWD' => 'root',
  'DB_PORT' => '3306',
  'DB_PREFIX' => 'tj_',
  'TMPL_ACTION_ERROR' => './view/msg.html',
  'TMPL_ACTION_SUCCESS' => './view/msg.html',
  'cfg_sitetitle' => '好统计',
  'cfg_seotitle' => '网站访客qq统计|获取网站访客qq系统|网页访客QQ抓取采集',
  'cfg_keyword' => '网站访客qq统计,获取网站访客qq系统,网页访客QQ抓取采集',
  'cfg_desc' => '  网站访客qq统计系统是一款在线获取网站访客qq的数据营销软件,让访客真正的成为客户不浪费任何一个意向客户,抓取采集网页qq访客统计系统为你提升10倍业绩',
  'cfg_regstatus' => '1',
  'cfg_isvip' => '1',
  'cfg_viptime' => '3',
  'cfg_close' => '1',
  'cfg_closemsg' => '网站暂时停止服务',
  'cfg_mailauto' => '1',
  'cfg_vipmprice' => '10',
  'cfg_vipyprice' => '20',
  'cfg_sitenum' => '10',
  'cfg_emailnum' => '100',
  'cfg_emailtplnum' => '100',
  'cfg_islogin' => '1',
  'cfg_api' => 'paipai',
);
?>